# Generated by Django 3.2.4 on 2021-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ownerClientId", models.IntegerField()),
                ("auctionId", models.IntegerField()),
                ("carModel", models.CharField(max_length=255)),
                ("vinNumber", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("recycle", models.IntegerField()),
                ("auctionFees", models.IntegerField()),
                ("salesFees", models.IntegerField()),
                ("status", models.BooleanField()),
                ("total", models.IntegerField()),
            ],
        ),
    ]
