# Generated by Django 3.2.4 on 2021-06-20 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CarSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "carModel",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vinNumber",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("price", models.IntegerField()),
                ("recycle", models.IntegerField()),
                ("auctionFees", models.IntegerField()),
                ("salesFees", models.IntegerField()),
                ("status", models.BooleanField()),
                ("total", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_sales",
                        to="auction.auction",
                    ),
                ),
                (
                    "ownerClient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_sales_as_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
