# Generated by Django 3.2.5 on 2021-08-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0007_auto_20210731_1625'),
        ('car_sale', '0002_alter_carsale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsale',
            name='carOrder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_sales', to='car_order.carorder'),
        ),
    ]
