# Generated by Django 3.2.5 on 2021-07-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0006_alter_carorder_client"),
        ("car_sale", "0003_auto_20210712_0744"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carsale",
            name="carOrder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="car_sales",
                to="car_order.carorder",
            ),
        ),
    ]
