# Generated by Django 3.2.4 on 2021-06-19 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=255)),
                ("milage", models.CharField(max_length=255)),
                ("body", models.CharField(max_length=255)),
                ("displacement", models.CharField(max_length=255)),
                ("complect", models.CharField(max_length=255)),
                ("condition", models.CharField(max_length=255)),
                ("price", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CarStoreImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.ImageField(upload_to="")),
                (
                    "car_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="car_store.carstore",
                    ),
                ),
            ],
        ),
    ]
