# Generated by Django 3.2.5 on 2021-07-23 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_auto_20210723_1214"),
        ("car_resale", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarResaleOldClientReplenishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_client_replenishment",
                        to="authorization.balance",
                    ),
                ),
                (
                    "car_resale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="old_client_replenishment",
                        to="car_resale.carresale",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarResaleNewClientWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_client_withdrawal",
                        to="authorization.balance",
                    ),
                ),
                (
                    "car_resale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_client_withdrawal",
                        to="car_resale.carresale",
                    ),
                ),
            ],
        ),
    ]
