# Generated by Django 3.2.9 on 2022-01-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_resale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carresale',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
