# Generated by Django 3.2.5 on 2021-07-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_resale', '0002_auto_20210711_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carresale',
            name='income',
        ),
    ]
