# Generated by Django 3.2.5 on 2021-07-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "car_resale",
            "0002_carresalenewclientwithdrawal_carresaleoldclientreplenishment",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="carresale",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="carresalenewclientwithdrawal",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="carresaleoldclientreplenishment",
            options={"ordering": ("id",)},
        ),
    ]
