version: 2.1

jobs:
  pull-and-build:
    docker:
      - image: cimg/base:2021.05
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: >
                  ssh
                  -oStrictHostKeyChecking=no
                  -v
                  $SSH_USER@$SSH_HOST
                  "sh /home/t2elzeth/sanri/backend_sanri/.circleci/deploy.sh"

workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - dev
