# Generated by Django 3.2.5 on 2021-08-23 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0002_auto_20210731_1625'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcar',
            name='body',
            field=models.CharField(default='sold', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcar',
            name='complect',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcar',
            name='condition',
            field=models.FloatField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcar',
            name='displacement',
            field=models.CharField(default='d', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcar',
            name='millage',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcar',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shop_cars', to='car_model.carmodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopcar',
            name='status',
            field=models.CharField(choices=[('for_sell', 'for_sell'), ('for_approve', 'for_approve'), ('sold', 'sold')], default='for_sell', max_length=255),
        ),
        migrations.AddField(
            model_name='shopcar',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
