# Generated by Django 3.2.5 on 2021-07-10 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car_model", "0003_rename_name_carmodel_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name="carmodel",
            old_name="model",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="carmodel",
            name="mark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="car_model.carmark",
            ),
        ),
    ]
