# Generated by Django 3.2.4 on 2021-06-19 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerWheelRecycling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContainerWheelSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dateOfSending', models.DateField()),
                ('commission', models.IntegerField()),
                ('containerTransportation', models.IntegerField()),
                ('packagingMaterials', models.IntegerField()),
                ('transportation', models.IntegerField()),
                ('loading', models.IntegerField()),
                ('status', models.IntegerField()),
                ('totalAmount', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to=settings.AUTH_USER_MODEL)),
                ('wheelRecycling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_recycling', to='container.containerwheelrecycling')),
                ('wheelSales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wheel_sales', to='container.containerwheelsales')),
            ],
        ),
    ]
