# Generated by Django 3.2.5 on 2021-07-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_auto_20210723_1214"),
        ("container", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerBalanceWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_withdrawal",
                        to="authorization.balance",
                    ),
                ),
                (
                    "container",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_withdrawal",
                        to="container.container",
                    ),
                ),
            ],
        ),
    ]
