# Generated by Django 3.2.5 on 2021-07-14 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0006_alter_carorder_client'),
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_cars', to='car_order.carorder')),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='container_cars', to='container.container')),
            ],
        ),
    ]
