# Generated by Django 3.2.5 on 2021-07-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_containerbalancewithdrawal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='containerbalancewithdrawal',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='containercar',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='wheelrecycling',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='wheelsales',
            options={'ordering': ('id',)},
        ),
    ]
