# Generated by Django 3.2.5 on 2021-07-14 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("container", "0004_alter_wheelsales_container"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CountAndSum",
        ),
    ]
