# Generated by Django 3.2.5 on 2021-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0005_delete_countandsum'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2003-11-22"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='containercar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2003-11-22"),
            preserve_default=False,
        ),
    ]
