# Generated by Django 3.2.5 on 2021-08-26 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authorization", "0001_initial"),
        ("car_model", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("transport_companies", "0001_initial"),
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lotNumber",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vinNumber",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "year",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("price", models.IntegerField()),
                ("recycle", models.IntegerField()),
                ("auctionFees", models.IntegerField()),
                ("transport", models.IntegerField()),
                ("fob", models.IntegerField()),
                ("amount", models.IntegerField(default=0)),
                (
                    "carNumber",
                    models.CharField(
                        choices=[
                            ("removed", "removed"),
                            ("not_removed", "not_removed"),
                            ("not_given", "not_given"),
                        ],
                        max_length=255,
                    ),
                ),
                ("documentsGiven", models.BooleanField(default=False)),
                ("total", models.IntegerField()),
                ("total_FOB", models.IntegerField()),
                ("total_FOB2", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("analysis", models.JSONField(default=dict)),
                (
                    "comment",
                    models.TextField(blank=True, default="", null=True),
                ),
                ("additional_expenses", models.IntegerField(default=0)),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auctions",
                        to="auction.auction",
                    ),
                ),
                (
                    "carModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_orders",
                        to="car_model.carmodel",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transportCompany",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_orders",
                        to="transport_companies.transportcompany",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="BalanceWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_order_withdrawals",
                        to="authorization.balance",
                    ),
                ),
                (
                    "car_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal",
                        to="car_order.carorder",
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
