# Generated by Django 3.2.4 on 2021-06-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clientId", models.IntegerField()),
                ("auctionId", models.IntegerField()),
                ("lotNumber", models.CharField(max_length=255)),
                ("carModel", models.CharField(max_length=255)),
                ("vinNumber", models.CharField(max_length=255)),
                ("year", models.CharField(max_length=255)),
                ("price", models.IntegerField()),
                ("recycle", models.IntegerField()),
                ("auctionFees", models.IntegerField()),
                ("transport", models.IntegerField()),
                ("fob", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("transportationCommission", models.IntegerField()),
                ("parking", models.IntegerField()),
                ("carNumber", models.BooleanField()),
                ("total", models.IntegerField()),
                ("total_FOB", models.IntegerField()),
            ],
        ),
    ]
