# Generated by Django 3.2.5 on 2021-07-23 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BalanceReplenishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                (
                    "car_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replenishment",
                        to="car_order.carorder",
                    ),
                ),
            ],
        ),
    ]
