# Generated by Django 3.2.5 on 2021-07-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carorder",
            name="amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
