# Generated by Django 3.2.5 on 2021-07-10 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0001_initial'),
        ('car_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='carModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_orders', to='car_model.carmodel'),
            preserve_default=False,
        ),
    ]
