# Generated by Django 3.2.5 on 2021-07-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0002_alter_carorder_carmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorder',
            name='transportationCommission',
        ),
    ]
