# Generated by Django 3.2.5 on 2021-08-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0002_alter_balancewithdrawal_car_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carorder',
            name='fob',
        ),
    ]
