# Generated by Django 3.2.5 on 2021-07-23 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0003_auto_20210723_1214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balancewithdrawal",
            name="car_order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawal",
                to="car_order.carorder",
            ),
        ),
    ]
