# Generated by Django 3.2.5 on 2021-07-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0003_remove_carorder_transportationcommission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='carNumber',
            field=models.CharField(choices=[('removed', 'removed'), ('not_removed', 'not_removed'), ('not_given', 'not_given')], max_length=255),
        ),
    ]
