# Generated by Django 3.2.5 on 2021-09-01 16:30

import car_order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0003_remove_carorder_fob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carorder",
            name="created_at",
            field=models.DateField(default=car_order.models.get_date),
        ),
    ]
