# Generated by Django 3.2.5 on 2021-07-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0003_carorder_documentsgiven"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carorder",
            name="parking",
        ),
    ]
