# Generated by Django 3.2.5 on 2021-07-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0004_remove_carorder_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
