# Generated by Django 3.2.5 on 2021-10-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0005_alter_carorder_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorder',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
