# Generated by Django 3.2.5 on 2021-07-12 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("car_order", "0005_alter_carorder_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carorder",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="car_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
