# Generated by Django 3.2.5 on 2021-10-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0006_carorder_is_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="carorder",
            name="is_shipped",
            field=models.BooleanField(default=False),
        ),
    ]
