# Generated by Django 3.2.5 on 2021-07-18 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_companies', '0001_initial'),
        ('car_order', '0006_alter_carorder_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorder',
            name='transportCompany',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_orders', to='transport_companies.transportcompany'),
            preserve_default=False,
        ),
    ]
