# Generated by Django 3.2.5 on 2021-07-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0006_auto_20210723_1857"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balancewithdrawal",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="carorder",
            options={"ordering": ("id",)},
        ),
    ]
