# Generated by Django 3.2.5 on 2021-08-14 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0007_auto_20210731_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carorder',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
