# Generated by Django 3.2.9 on 2021-11-20 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0008_carorder_fob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancewithdrawal',
            name='car_order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal', to='car_order.carorder'),
        ),
    ]
