# Generated by Django 3.2.5 on 2021-08-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0008_alter_carorder_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorder',
            name='additional_expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carorder',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
