# Generated by Django 3.2.5 on 2021-08-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_order', '0009_auto_20210814_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='carorder',
            name='total_FOB2',
            field=models.IntegerField(default=0),
        ),
    ]
