# Generated by Django 3.2.5 on 2021-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_order", "0010_carorder_total_fob2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carorder",
            name="comment",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
