# Generated by Django 3.2.9 on 2022-01-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
