# Generated by Django 3.2.5 on 2021-07-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0002_auto_20210711_2130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
