# Generated by Django 3.2.4 on 2021-06-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyPaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('from_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='container.container')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='monthly_payment.monthlypaymenttype')),
            ],
        ),
    ]
