from django.core.management.base import BaseCommand

from car_model.models import CarMark

marks = {
    "TOYOTA": (
        "ALLEX",
        "ALLION",
        "ALPHARD",
        "ALTEZZA",
        "AQUA",
        "ARISTO",
        "AURIS",
        "AVENSIS",
        "BELTA",
        "BLADE",
        "C-HR",
        "WINDOM",
        "WISH",
        "VOXY",
        "VITZ",
        "RAV4",
        "RAUM",
        "TOWN",
        "ACE",
        "PRIUS",
        "NOAH",
        "PASSO",
        "LITE",
        "ACE",
        "MARK",
        "II",
        "MARK",
        "HILUX",
        "SURF",
        "IPSUM",
        "IST",
        "KLUGER",
        "LAND",
        "CRUISER",
        "PRADO",
        "LAND",
        "CRUISER",
        "PRADO",
        "HARRIER",
        "ESTIMA",
        "CAMRY",
        "CALDINA",
        "CAMI",
        "CAMROAD",
        "CARINA",
        "CELICA",
        "CELSIOR",
        "CENTURY",
        "CHASER",
        "COASTER",
        "COMFORT",
        "COROLLA",
        "CORONA",
        "CROWN",
        "CURREN",
        "DUET",
        "DYNA",
        "E-S",
        "TRUCK",
        "ESQUIRE",
        "FJ",
        "CRUISER",
        "FORKLIFT",
        "FUNCARGO",
        "GAIA",
        "GR",
        "YARIS",
        "GRANACE",
        "GRAND",
        "ASH",
        "ES",
        "GRANVIA",
        "HIACE",
        "MIRAI",
        "OPA",
        "ORIGIN",
        "PREMIO",
        "PROBOX",
        "QUICK",
        "DELIVERY",
        "RACTIS",
        "RAIZE",
        "RUSH",
        "SAI",
        "SEQUOIA",
        "SPARKY",
        "SPRINTER",
        "SUPRA",
        "VANGUARD",
        "VEROSSA",
        "WILL",
        "YARIS",
    ),
    "HONDA": (
        "FIT",
        "INSIGHT",
        "HR-V",
        "ACCORD",
        "ACTY",
        "AIRWAVE",
        "ASCOT",
        "AVANCIER",
        "BEAT",
        "CIVIC",
        "CR-V",
        "CR-X",
        "CR-Z",
        "CROSSROAD",
        "ELYSION",
        "FREED",
        "INSPIRE",
        "INTEGRA",
        "LIFE",
        "N BOX",
        "ODYSSEY",
        "SHUTTLE",
        "STEP WAGON",
        "STREAM",
        "TORNEO",
        "TODAY",
        "SABER",
    ),
    "NISSAN": (
        "180 SX",
        "ATLAS",
        "AVENIR WAGON",
        "BE-1",
        "BIGTHUMB",
        "BLUEBIRD",
        "BLUEBIRD SYLPHY",
        "CARAVAN",
        "CEDRIC",
        "CEFIRO",
        "CIMA",
        "CIVILIAN",
        "CLIPPER",
        "CONDOR",
        "CRUE",
        "CUBE",
        "CUBECUBIC",
        "DATSUN",
        "DAYZ",
        "DUALIS",
        "ELGRAND",
        "EXPERT",
        "FAIRLADYZ",
        "FIGARO",
        "FORKLIFT",
        "FUGA",
        "GLORIA",
        "GT-R",
        "HOMY",
        "INFINITI",
        "JUKE",
        "KIX",
        "LAFESTA",
        "LARGO",
        "LATIO",
        "LAUREL",
        "LEAF",
        "LEOPARD",
        "LIBERTY",
        "MARCH",
        "MAXIMA",
        "MICRA",
        "MOCO",
        "MURANO",
        "NOTE",
        "NT100 CLIPPER",
        "NT450 ATLAS",
        "NV CARAVAN MIKE",
        "NV100 CLIPPER",
        "NV150",
        "NV200",
        "NV350",
        "OTTI",
        "PAO",
        "PINO",
        "PRESAGE",
        "PRESEA",
        "PRESIDENT",
        "PRIMERA",
        "PULSAR",
        "QUON",
        "RASHEEN",
        "RNESSA",
        "ROOX",
        "SAFARI",
        "SANTANA",
        "SERENA",
        "SILVIA",
        "SKYLINE",
        "SPACE",
        "STAGEA",
        "SUNNY",
        "TEANA",
        "TERRANO",
        "TIIDA",
        "TRUCK",
        "UD SERIES",
        "VANETTE TRUCK",
        "VANETTE VAN",
        "WINGROAD",
        "X-TRAIL",
    ),
    "SUBARU": (
        "ALCYONE SVX",
        "BRZ",
        "CHIFFON",
        "DEX",
        "DIAS WAGON",
        "EXIGA",
        "FORESTER",
        "GOLF ALLTRACK",
        "IMPREZA",
        "JUSTY",
        "LEGACY",
        "LEVORG",
        "LUCRA",
        "OUTBACK",
        "PLEO",
        "R1",
        "R2",
        "SAMBAR",
        "STELLA",
        "XV",
        "TRAVIQ",
        "TREZIA",
        "VIVIO",
        "WRX",
    ),
    "AUDI": (
        "A1",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "ALLROAD",
        "Q2",
        "Q3",
        "Q5",
        "Q7",
        "R8",
        "RS",
        "Q3",
        "RS3",
        "RS4",
        "RS5",
        "RS6",
        "S3",
        "S4",
        "S5",
        "S6",
        "S8",
        "SQ5",
        "TT",
        "TTCOUPE",
    ),
    "VOLKSWAGEN": (
        "BORA",
        "ARTEON",
        "BEETLE",
        "CALIFORNIA",
        "CC",
        "POLO",
        "CROSS",
        "EOS",
        "GOLF",
        "JETTA",
        "LUPO",
        "NEW BEETLE",
        "PASSAT",
        "RUPO",
        "SCIROCCO",
        "SHARAN",
        "SIROCCO",
        "T-CROSS",
        "T-ROC",
        "THE BEETLE",
        "TIGUAN",
        "TOUAREG",
        "TYPE",
        "UP",
        "VANAGON",
        "VOLKSWAGEN",
    ),
    "MERCEDES BENZ": (
        "190 CLASS ",
        "190 SERIES",
        "500S ",
        "A CLASS ",
        "AMG ",
        "AMG A CLASS ",
        "AMG C ",
        "AMG C CLASS ",
        "AMG CLA SHOOTING BRAKE ",
        "AMG E CLASS ",
        "AMG G CLASS ",
        "AMG GLC ",
        "AMG GLE ",
        "AMG SLK ",
        "B CLASS",
        "C CLASS ",
        "CL CLASS ",
        "CLA CLASS ",
        "CLA SHOOTING BRAKE ",
        "CLK CLASS ",
        "CLS ",
        "CLS CLASS ",
        "CLS SHOOTING BRAKE",
        "E CLASS ",
        "E CLASS STATION WAGON ",
        "E CLASS WAGON ",
        "E-CLASS ALL-TERRAIN",
        "G CLASS ",
        "GELANDEWAGEN ",
        "GL CLASS ",
        "GLA CLASS ",
        "GLC CLASS ",
        "GLE CLASS ",
        "GLK CLASS ",
        "GT S",
        "M CLASS ",
        "MB",
        "MB AKLA SEDAN ",
        "MB C STATION ",
        "MB CLA CLASS ",
        "MB CLA SHOE TIB ",
        "MB EQC ",
        "MB G CLASS 5D4W ",
        "MB GLA CLASS ",
        "MB GLB ",
        "MB GLC ",
        "MB GLE ",
        "MB GLS ",
        "MBU UNIMOG 2D4W ",
        "MEDIUM CLASS",
        "ML CLASS ",
        "OTHER ",
        "R CLASS ",
        "S CLASS ",
        "SL SERIES ",
        "SLK CLASS ",
        "UNIMOG",
        "V CLASS ",
        "VIANO",
    ),
    "BMW": [],
    "MAZDA": (
        "ATENZA",
        "AXELA",
        "AZ",
        "BIANTE",
        "BONGO",
        "CAPELLA",
        "CAROL",
        "COSMO",
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-7",
        "CX-8",
        "DEMIO",
        "EUNOS",
        "FAMILIA",
        "FLAIR",
        "LAPUTA",
        "MILLENIA",
        "MPV",
        "PREMACY",
        "PROCEED",
        "ROADSTER",
        "RX-7",
        "RX-8",
        "SCRUM",
        "SENTIA",
        "SPIANO",
        "TITAN",
        "TRIBUTE",
        "VERISA",
    ),
    "MITSUBISHI": (
        "AERO",
        "AIRTREK",
        "BRAVO",
        "BUS",
        "CANTER",
        "CHALLENGER",
        "COLT",
        "CX-3",
        "DELICA",
        "DIAMANTE",
        "DINGO",
        "DION",
        "ECLIPSE",
        "EK ACTIVE",
        "EK CROSS",
        "EK CUSTOM",
        "EK SPACE",
        "EK SPORTS",
        "EK WAGON",
        "EK X",
        "FORKLIFT",
        "FTO",
        "FUSO",
        "GALANT",
        "GRANDIS",
        "GREAT",
        "GTO",
        "JEEP",
        "LANCER",
        "LEGNUM",
        "MINICA",
        "MIRAGE",
        "OUTLANDER",
        "PAJERO",
        "ROSA",
        "RVR",
        "SUPER GREAT",
        "TOPPO",
        "TOWNBOX",
        "TRITON",
        "WHEELLOADER",
    ),
    "SUZUKI": [],
    "ISUZU": [],
    "TADANO": [],
    "TCM": [],
    "YANMAR": [],
    "DAIHATSU": [],
    "MITSUOKA": [],
    "KAWASAKI": [],
    "KOMATSU": [],
    "LEXUS": [],
    "CHEVROLET": [],
    "RENAULT": [],
    "DODGE": [],
    "FERRARI": [],
    "FIAT": [],
    "FORD": [],
    "GMC": [],
    "HINO": [],
    "INFINITI": [],
    "JEEP": [],
    "OPEL": [],
    "TESLA": [],
    "VOLVO": [],
    "FORKLIFT": [],
}


class Command(BaseCommand):
    def handle(self, *args, **options):
        counter = 0
        for mark, models in marks.items():
            car_mark, created = CarMark.objects.get_or_create(name=mark)

            if not created:
                print(f"Mark {car_mark.name} already exists")
            else:
                print(f"Created CarMark: {car_mark.name}")

            for model in models:
                car_model, created = car_mark.models.get_or_create(name=model)
                if created:
                    print(f"CarModel {model} created!")
                else:
                    print(f"CarModel {model} already exists")

            counter += 1

        print(f"Created {counter} marks in total")
