# Generated by Django 3.2.5 on 2021-09-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10
            ),
        ),
    ]
