# Generated by Django 3.2.5 on 2021-07-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='name',
        ),
    ]
