# Generated by Django 3.2.4 on 2021-06-30 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="balance",
            name="client",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="balances",
                to="authorization.user",
            ),
            preserve_default=False,
        ),
    ]
