# Generated by Django 3.2.9 on 2021-11-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_balance_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='transportation_limit',
            field=models.IntegerField(default=6000),
        ),
    ]
