# Generated by Django 3.2.4 on 2021-07-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_balance_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("client", "client"),
                    ("employee", "employee"),
                ],
                default="user",
                max_length=255,
            ),
        ),
    ]
