# Generated by Django 3.2.5 on 2021-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_manageduser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="rate",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="balance",
            name="sum_in_usa",
            field=models.IntegerField(default=0),
        ),
    ]
