# Generated by Django 3.2.5 on 2021-07-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_auto_20210723_1214"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="balance",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="manageduser",
            options={"ordering": ("id",)},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("id",)},
        ),
    ]
