# Generated by Django 3.2.5 on 2021-07-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_balance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sizeFOB',
            field=models.IntegerField(default=0),
        ),
    ]
