# Generated by Django 3.2.5 on 2021-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service',
            field=models.CharField(choices=[('dissection', 'dissection'), ('entire', 'entire')], default='entire', max_length=255),
        ),
    ]
