# Generated by Django 3.2.5 on 2021-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0005_alter_user_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="atWhatPrice",
            field=models.CharField(
                choices=[("by_fact", "by_fact"), ("by_fob", "by_fob")],
                default="by_fact",
                max_length=255,
            ),
        ),
    ]
