# Generated by Django 3.2.5 on 2021-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_alter_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2003-11-22"),
            preserve_default=False,
        ),
    ]
